import Vue from 'vue'
import Router from 'vue-router'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _7a6dbb4c = () => interopDefault(import('~/pages/dashboard/sales/index.vue' /* webpackChunkName: "" */))
const _1d2012e6 = () => interopDefault(import('../pages/widgets/index.vue' /* webpackChunkName: "pages/widgets/index" */))
const _3aaae204 = () => interopDefault(import('../pages/account/forgot-password.vue' /* webpackChunkName: "pages/account/forgot-password" */))
const _f1dd20bc = () => interopDefault(import('../pages/account/login.vue' /* webpackChunkName: "pages/account/login" */))
const _7742240c = () => interopDefault(import('../pages/account/register.vue' /* webpackChunkName: "pages/account/register" */))
const _92ff664e = () => interopDefault(import('../pages/apps/calendar/index.vue' /* webpackChunkName: "pages/apps/calendar/index" */))
const _7f47e71a = () => interopDefault(import('../pages/apps/chat/index.vue' /* webpackChunkName: "pages/apps/chat/index" */))
const _3a3b9336 = () => interopDefault(import('../pages/apps/companies/index.vue' /* webpackChunkName: "pages/apps/companies/index" */))
const _966a9e18 = () => interopDefault(import('../pages/apps/file-manager.vue' /* webpackChunkName: "pages/apps/file-manager" */))
const _5f00c942 = () => interopDefault(import('../pages/apps/tickets/index.vue' /* webpackChunkName: "pages/apps/tickets/index" */))
const _53d918c6 = () => interopDefault(import('../pages/auth/confirm-mail.vue' /* webpackChunkName: "pages/auth/confirm-mail" */))
const _873a1f2a = () => interopDefault(import('../pages/auth/confirm-mail-2.vue' /* webpackChunkName: "pages/auth/confirm-mail-2" */))
const _6b70b21c = () => interopDefault(import('../pages/auth/lock-screen.vue' /* webpackChunkName: "pages/auth/lock-screen" */))
const _4c798c41 = () => interopDefault(import('../pages/auth/lock-screen-2.vue' /* webpackChunkName: "pages/auth/lock-screen-2" */))
const _dcf02592 = () => interopDefault(import('../pages/auth/login.vue' /* webpackChunkName: "pages/auth/login" */))
const _49ae6c9c = () => interopDefault(import('../pages/auth/login-2.vue' /* webpackChunkName: "pages/auth/login-2" */))
const _26f27ba8 = () => interopDefault(import('../pages/auth/logout.vue' /* webpackChunkName: "pages/auth/logout" */))
const _3f684f5e = () => interopDefault(import('../pages/auth/logout-2.vue' /* webpackChunkName: "pages/auth/logout-2" */))
const _6733737b = () => interopDefault(import('../pages/auth/recoverpwd.vue' /* webpackChunkName: "pages/auth/recoverpwd" */))
const _629171e0 = () => interopDefault(import('../pages/auth/recoverpwd-2.vue' /* webpackChunkName: "pages/auth/recoverpwd-2" */))
const _573f0c45 = () => interopDefault(import('../pages/auth/register.vue' /* webpackChunkName: "pages/auth/register" */))
const _7e1a002a = () => interopDefault(import('../pages/auth/register-2.vue' /* webpackChunkName: "pages/auth/register-2" */))
const _301e2c71 = () => interopDefault(import('../pages/auth/signin-signup.vue' /* webpackChunkName: "pages/auth/signin-signup" */))
const _c89c7554 = () => interopDefault(import('../pages/auth/signin-signup-2.vue' /* webpackChunkName: "pages/auth/signin-signup-2" */))
const _4207acba = () => interopDefault(import('../pages/charts/apex/index.vue' /* webpackChunkName: "pages/charts/apex/index" */))
const _17c19188 = () => interopDefault(import('../pages/charts/c3/index.vue' /* webpackChunkName: "pages/charts/c3/index" */))
const _0ef1f484 = () => interopDefault(import('../pages/charts/chartist/index.vue' /* webpackChunkName: "pages/charts/chartist/index" */))
const _5d232836 = () => interopDefault(import('../pages/charts/chartjs/index.vue' /* webpackChunkName: "pages/charts/chartjs/index" */))
const _41c0d26a = () => interopDefault(import('../pages/charts/knob.vue' /* webpackChunkName: "pages/charts/knob" */))
const _463dfc16 = () => interopDefault(import('../pages/contacts/list.vue' /* webpackChunkName: "pages/contacts/list" */))
const _13a254bc = () => interopDefault(import('../pages/contacts/profile.vue' /* webpackChunkName: "pages/contacts/profile" */))
const _3b7c6bae = () => interopDefault(import('../pages/dashboard/analytics/index.vue' /* webpackChunkName: "pages/dashboard/analytics/index" */))
const _1aaa8881 = () => interopDefault(import('../pages/dashboard/crm/index.vue' /* webpackChunkName: "pages/dashboard/crm/index" */))
const _37d8e7a2 = () => interopDefault(import('../pages/dashboard/sales/index.vue' /* webpackChunkName: "pages/dashboard/sales/index" */))
const _0ec3d184 = () => interopDefault(import('../pages/ecommerce/cart.vue' /* webpackChunkName: "pages/ecommerce/cart" */))
const _c20f4aac = () => interopDefault(import('../pages/ecommerce/checkout.vue' /* webpackChunkName: "pages/ecommerce/checkout" */))
const _86671c38 = () => interopDefault(import('../pages/ecommerce/customers/index.vue' /* webpackChunkName: "pages/ecommerce/customers/index" */))
const _8e8f8f88 = () => interopDefault(import('../pages/ecommerce/data-products.js' /* webpackChunkName: "pages/ecommerce/data-products" */))
const _57d8ca14 = () => interopDefault(import('../pages/ecommerce/order-detail.vue' /* webpackChunkName: "pages/ecommerce/order-detail" */))
const _14ff50e8 = () => interopDefault(import('../pages/ecommerce/orders/index.vue' /* webpackChunkName: "pages/ecommerce/orders/index" */))
const _20824404 = () => interopDefault(import('../pages/ecommerce/product-create.vue' /* webpackChunkName: "pages/ecommerce/product-create" */))
const _03f59f6a = () => interopDefault(import('../pages/ecommerce/products/index.vue' /* webpackChunkName: "pages/ecommerce/products/index" */))
const _2de97edb = () => interopDefault(import('../pages/ecommerce/products-grid.vue' /* webpackChunkName: "pages/ecommerce/products-grid" */))
const _1a511bc0 = () => interopDefault(import('../pages/ecommerce/sellers.vue' /* webpackChunkName: "pages/ecommerce/sellers" */))
const _2f7b83f8 = () => interopDefault(import('../pages/email/data-inbox.js' /* webpackChunkName: "pages/email/data-inbox" */))
const _fc5658a4 = () => interopDefault(import('../pages/email/inbox.vue' /* webpackChunkName: "pages/email/inbox" */))
const _360ab8b5 = () => interopDefault(import('../pages/email/sidepanel.vue' /* webpackChunkName: "pages/email/sidepanel" */))
const _a4a0ca3e = () => interopDefault(import('../pages/email/templates.vue' /* webpackChunkName: "pages/email/templates" */))
const _5670d3ba = () => interopDefault(import('../pages/email/toolbar.vue' /* webpackChunkName: "pages/email/toolbar" */))
const _d4b4bb86 = () => interopDefault(import('../pages/extended/rangeslider.vue' /* webpackChunkName: "pages/extended/rangeslider" */))
const _d5aec224 = () => interopDefault(import('../pages/extended/scrollspy.vue' /* webpackChunkName: "pages/extended/scrollspy" */))
const _1070dcc4 = () => interopDefault(import('../pages/extended/sweet-alert.vue' /* webpackChunkName: "pages/extended/sweet-alert" */))
const _344736ee = () => interopDefault(import('../pages/extended/tour.vue' /* webpackChunkName: "pages/extended/tour" */))
const _d9e0a0fe = () => interopDefault(import('../pages/extras/404.vue' /* webpackChunkName: "pages/extras/404" */))
const _4f84735d = () => interopDefault(import('../pages/extras/404-alt.vue' /* webpackChunkName: "pages/extras/404-alt" */))
const _7084e684 = () => interopDefault(import('../pages/extras/500.vue' /* webpackChunkName: "pages/extras/500" */))
const _73ced290 = () => interopDefault(import('../pages/extras/coming-soon.vue' /* webpackChunkName: "pages/extras/coming-soon" */))
const _b694cab8 = () => interopDefault(import('../pages/extras/faqs.vue' /* webpackChunkName: "pages/extras/faqs" */))
const _35483314 = () => interopDefault(import('../pages/extras/invoice.vue' /* webpackChunkName: "pages/extras/invoice" */))
const _254a2008 = () => interopDefault(import('../pages/extras/lightbox.vue' /* webpackChunkName: "pages/extras/lightbox" */))
const _a9bd9a48 = () => interopDefault(import('../pages/extras/maintenance.vue' /* webpackChunkName: "pages/extras/maintenance" */))
const _759c4e8f = () => interopDefault(import('../pages/extras/pricing.vue' /* webpackChunkName: "pages/extras/pricing" */))
const _781ca698 = () => interopDefault(import('../pages/extras/search-results.vue' /* webpackChunkName: "pages/extras/search-results" */))
const _eb5d6804 = () => interopDefault(import('../pages/extras/sitemap.vue' /* webpackChunkName: "pages/extras/sitemap" */))
const _6fe13a50 = () => interopDefault(import('../pages/extras/starter.vue' /* webpackChunkName: "pages/extras/starter" */))
const _58551548 = () => interopDefault(import('../pages/extras/timeline.vue' /* webpackChunkName: "pages/extras/timeline" */))
const _4550e477 = () => interopDefault(import('../pages/forms/advanced.vue' /* webpackChunkName: "pages/forms/advanced" */))
const _7ef7cacc = () => interopDefault(import('../pages/forms/elements.vue' /* webpackChunkName: "pages/forms/elements" */))
const _53b87d96 = () => interopDefault(import('../pages/forms/file-uploads.vue' /* webpackChunkName: "pages/forms/file-uploads" */))
const _605e167e = () => interopDefault(import('../pages/forms/mask.vue' /* webpackChunkName: "pages/forms/mask" */))
const _e6133500 = () => interopDefault(import('../pages/forms/quill.vue' /* webpackChunkName: "pages/forms/quill" */))
const _242b060e = () => interopDefault(import('../pages/forms/validation.vue' /* webpackChunkName: "pages/forms/validation" */))
const _f502ff00 = () => interopDefault(import('../pages/forms/wizard.vue' /* webpackChunkName: "pages/forms/wizard" */))
const _e6830e0e = () => interopDefault(import('../pages/icons/boxicons.vue' /* webpackChunkName: "pages/icons/boxicons" */))
const _b88bc258 = () => interopDefault(import('../pages/icons/data-fontawesome.js' /* webpackChunkName: "pages/icons/data-fontawesome" */))
const _509a527f = () => interopDefault(import('../pages/icons/data-material.js' /* webpackChunkName: "pages/icons/data-material" */))
const _d6c0dd42 = () => interopDefault(import('../pages/icons/data-remix.js' /* webpackChunkName: "pages/icons/data-remix" */))
const _4e6b8c6e = () => interopDefault(import('../pages/icons/feather.vue' /* webpackChunkName: "pages/icons/feather" */))
const _5f304ca2 = () => interopDefault(import('../pages/icons/font-awesome.vue' /* webpackChunkName: "pages/icons/font-awesome" */))
const _2398ae58 = () => interopDefault(import('../pages/icons/mdi.vue' /* webpackChunkName: "pages/icons/mdi" */))
const _25a0e0ef = () => interopDefault(import('../pages/icons/remix.vue' /* webpackChunkName: "pages/icons/remix" */))
const _880bcecc = () => interopDefault(import('../pages/icons/weather.vue' /* webpackChunkName: "pages/icons/weather" */))
const _4b6951e8 = () => interopDefault(import('../pages/maps/google.vue' /* webpackChunkName: "pages/maps/google" */))
const _7987d12a = () => interopDefault(import('../pages/tables/advanced/index.vue' /* webpackChunkName: "pages/tables/advanced/index" */))
const _7138468e = () => interopDefault(import('../pages/tables/basic.vue' /* webpackChunkName: "pages/tables/basic" */))
const _09f9d514 = () => interopDefault(import('../pages/task/detail.vue' /* webpackChunkName: "pages/task/detail" */))
const _18a71adf = () => interopDefault(import('../pages/task/kanban/index.vue' /* webpackChunkName: "pages/task/kanban/index" */))
const _6fa21e83 = () => interopDefault(import('../pages/task/list.vue' /* webpackChunkName: "pages/task/list" */))
const _1ea51434 = () => interopDefault(import('../pages/ui/avatars.vue' /* webpackChunkName: "pages/ui/avatars" */))
const _c3cf240a = () => interopDefault(import('../pages/ui/buttons.vue' /* webpackChunkName: "pages/ui/buttons" */))
const _0e9d855d = () => interopDefault(import('../pages/ui/cards.vue' /* webpackChunkName: "pages/ui/cards" */))
const _200b4bd6 = () => interopDefault(import('../pages/ui/carousel.vue' /* webpackChunkName: "pages/ui/carousel" */))
const _61041808 = () => interopDefault(import('../pages/ui/dropdowns.vue' /* webpackChunkName: "pages/ui/dropdowns" */))
const _3a4dabe2 = () => interopDefault(import('../pages/ui/general.vue' /* webpackChunkName: "pages/ui/general" */))
const _8e129c88 = () => interopDefault(import('../pages/ui/grid.vue' /* webpackChunkName: "pages/ui/grid" */))
const _1687806e = () => interopDefault(import('../pages/ui/images.vue' /* webpackChunkName: "pages/ui/images" */))
const _556d9f86 = () => interopDefault(import('../pages/ui/list-group.vue' /* webpackChunkName: "pages/ui/list-group" */))
const _1666325c = () => interopDefault(import('../pages/ui/modals.vue' /* webpackChunkName: "pages/ui/modals" */))
const _0b46333c = () => interopDefault(import('../pages/ui/notifications.vue' /* webpackChunkName: "pages/ui/notifications" */))
const _1c6227af = () => interopDefault(import('../pages/ui/portlets.vue' /* webpackChunkName: "pages/ui/portlets" */))
const _376703ba = () => interopDefault(import('../pages/ui/progress.vue' /* webpackChunkName: "pages/ui/progress" */))
const _83655252 = () => interopDefault(import('../pages/ui/ribbons.vue' /* webpackChunkName: "pages/ui/ribbons" */))
const _f6f64220 = () => interopDefault(import('../pages/ui/spinners.vue' /* webpackChunkName: "pages/ui/spinners" */))
const _27940c58 = () => interopDefault(import('../pages/ui/tabs-accordions.vue' /* webpackChunkName: "pages/ui/tabs-accordions" */))
const _3ca9cc76 = () => interopDefault(import('../pages/ui/tooltips-popovers.vue' /* webpackChunkName: "pages/ui/tooltips-popovers" */))
const _3dd660a5 = () => interopDefault(import('../pages/ui/typography.vue' /* webpackChunkName: "pages/ui/typography" */))
const _6ba06675 = () => interopDefault(import('../pages/ui/video.vue' /* webpackChunkName: "pages/ui/video" */))
const _598432f0 = () => interopDefault(import('../pages/widgets/data.js' /* webpackChunkName: "pages/widgets/data" */))
const _0980eb07 = () => interopDefault(import('../pages/apps/calendar/data-calendar.js' /* webpackChunkName: "pages/apps/calendar/data-calendar" */))
const _40288a56 = () => interopDefault(import('../pages/apps/chat/data.js' /* webpackChunkName: "pages/apps/chat/data" */))
const _3ab0e5d9 = () => interopDefault(import('../pages/apps/companies/data.js' /* webpackChunkName: "pages/apps/companies/data" */))
const _a1b7a236 = () => interopDefault(import('../pages/apps/tickets/data.js' /* webpackChunkName: "pages/apps/tickets/data" */))
const _22fd905d = () => interopDefault(import('../pages/charts/apex/data.js' /* webpackChunkName: "pages/charts/apex/data" */))
const _e0335eaa = () => interopDefault(import('../pages/charts/c3/data.js' /* webpackChunkName: "pages/charts/c3/data" */))
const _1c8b42a7 = () => interopDefault(import('../pages/charts/chartist/data.js' /* webpackChunkName: "pages/charts/chartist/data" */))
const _961f6d30 = () => interopDefault(import('../pages/charts/chartjs/BarChart.vue' /* webpackChunkName: "pages/charts/chartjs/BarChart" */))
const _ebb54c0e = () => interopDefault(import('../pages/charts/chartjs/DonutChart.vue' /* webpackChunkName: "pages/charts/chartjs/DonutChart" */))
const _7c3cd1bd = () => interopDefault(import('../pages/charts/chartjs/LineChart.vue' /* webpackChunkName: "pages/charts/chartjs/LineChart" */))
const _60122c0f = () => interopDefault(import('../pages/charts/chartjs/PieChart.vue' /* webpackChunkName: "pages/charts/chartjs/PieChart" */))
const _f292ad46 = () => interopDefault(import('../pages/charts/chartjs/PolarChart.vue' /* webpackChunkName: "pages/charts/chartjs/PolarChart" */))
const _01bab695 = () => interopDefault(import('../pages/charts/chartjs/RadarChart.vue' /* webpackChunkName: "pages/charts/chartjs/RadarChart" */))
const _9d1d8b6e = () => interopDefault(import('../pages/dashboard/analytics/channels.vue' /* webpackChunkName: "pages/dashboard/analytics/channels" */))
const _5b670772 = () => interopDefault(import('../pages/dashboard/analytics/overview.vue' /* webpackChunkName: "pages/dashboard/analytics/overview" */))
const _0ab5d97d = () => interopDefault(import('../pages/dashboard/analytics/social-media.vue' /* webpackChunkName: "pages/dashboard/analytics/social-media" */))
const _43d8664f = () => interopDefault(import('../pages/dashboard/analytics/sources.vue' /* webpackChunkName: "pages/dashboard/analytics/sources" */))
const _27aba45f = () => interopDefault(import('../pages/dashboard/analytics/users.vue' /* webpackChunkName: "pages/dashboard/analytics/users" */))
const _27a59807 = () => interopDefault(import('../pages/ecommerce/customers/data.js' /* webpackChunkName: "pages/ecommerce/customers/data" */))
const _6be6c7af = () => interopDefault(import('../pages/ecommerce/orders/data.js' /* webpackChunkName: "pages/ecommerce/orders/data" */))
const _70f8c42e = () => interopDefault(import('../pages/ecommerce/products/data.js' /* webpackChunkName: "pages/ecommerce/products/data" */))
const _281c10cd = () => interopDefault(import('../pages/tables/advanced/data.js' /* webpackChunkName: "pages/tables/advanced/data" */))
const _4307787c = () => interopDefault(import('../pages/task/kanban/data.js' /* webpackChunkName: "pages/task/kanban/data" */))
const _731a4efe = () => interopDefault(import('../pages/ecommerce/product-detail/_id.vue' /* webpackChunkName: "pages/ecommerce/product-detail/_id" */))
const _767f6f99 = () => interopDefault(import('../pages/email/reademail/_id.vue' /* webpackChunkName: "pages/email/reademail/_id" */))

// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: decodeURI('/'),
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/ar",
    component: _7a6dbb4c
  }, {
    path: "/es",
    component: _7a6dbb4c
  }, {
    path: "/fr",
    component: _7a6dbb4c
  }, {
    path: "/widgets",
    component: _1d2012e6,
    name: "widgets___en"
  }, {
    path: "/account/forgot-password",
    component: _3aaae204,
    name: "account-forgot-password___en"
  }, {
    path: "/account/login",
    component: _f1dd20bc,
    name: "account-login___en"
  }, {
    path: "/account/register",
    component: _7742240c,
    name: "account-register___en"
  }, {
    path: "/apps/calendar",
    component: _92ff664e,
    name: "apps-calendar___en"
  }, {
    path: "/apps/chat",
    component: _7f47e71a,
    name: "apps-chat___en"
  }, {
    path: "/apps/companies",
    component: _3a3b9336,
    name: "apps-companies___en"
  }, {
    path: "/apps/file-manager",
    component: _966a9e18,
    name: "apps-file-manager___en"
  }, {
    path: "/apps/tickets",
    component: _5f00c942,
    name: "apps-tickets___en"
  }, {
    path: "/ar/widgets",
    component: _1d2012e6,
    name: "widgets___ar"
  }, {
    path: "/auth/confirm-mail",
    component: _53d918c6,
    name: "auth-confirm-mail___en"
  }, {
    path: "/auth/confirm-mail-2",
    component: _873a1f2a,
    name: "auth-confirm-mail-2___en"
  }, {
    path: "/auth/lock-screen",
    component: _6b70b21c,
    name: "auth-lock-screen___en"
  }, {
    path: "/auth/lock-screen-2",
    component: _4c798c41,
    name: "auth-lock-screen-2___en"
  }, {
    path: "/auth/login",
    component: _dcf02592,
    name: "auth-login___en"
  }, {
    path: "/auth/login-2",
    component: _49ae6c9c,
    name: "auth-login-2___en"
  }, {
    path: "/auth/logout",
    component: _26f27ba8,
    name: "auth-logout___en"
  }, {
    path: "/auth/logout-2",
    component: _3f684f5e,
    name: "auth-logout-2___en"
  }, {
    path: "/auth/recoverpwd",
    component: _6733737b,
    name: "auth-recoverpwd___en"
  }, {
    path: "/auth/recoverpwd-2",
    component: _629171e0,
    name: "auth-recoverpwd-2___en"
  }, {
    path: "/auth/register",
    component: _573f0c45,
    name: "auth-register___en"
  }, {
    path: "/auth/register-2",
    component: _7e1a002a,
    name: "auth-register-2___en"
  }, {
    path: "/auth/signin-signup",
    component: _301e2c71,
    name: "auth-signin-signup___en"
  }, {
    path: "/auth/signin-signup-2",
    component: _c89c7554,
    name: "auth-signin-signup-2___en"
  }, {
    path: "/charts/apex",
    component: _4207acba,
    name: "charts-apex___en"
  }, {
    path: "/charts/c3",
    component: _17c19188,
    name: "charts-c3___en"
  }, {
    path: "/charts/chartist",
    component: _0ef1f484,
    name: "charts-chartist___en"
  }, {
    path: "/charts/chartjs",
    component: _5d232836,
    name: "charts-chartjs___en"
  }, {
    path: "/charts/knob",
    component: _41c0d26a,
    name: "charts-knob___en"
  }, {
    path: "/contacts/list",
    component: _463dfc16,
    name: "contacts-list___en"
  }, {
    path: "/contacts/profile",
    component: _13a254bc,
    name: "contacts-profile___en"
  }, {
    path: "/dashboard/analytics",
    component: _3b7c6bae,
    name: "dashboard-analytics___en"
  }, {
    path: "/dashboard/crm",
    component: _1aaa8881,
    name: "dashboard-crm___en"
  }, {
    path: "/dashboard/sales",
    component: _37d8e7a2,
    name: "dashboard-sales___en"
  }, {
    path: "/ecommerce/cart",
    component: _0ec3d184,
    name: "ecommerce-cart___en"
  }, {
    path: "/ecommerce/checkout",
    component: _c20f4aac,
    name: "ecommerce-checkout___en"
  }, {
    path: "/ecommerce/customers",
    component: _86671c38,
    name: "ecommerce-customers___en"
  }, {
    path: "/ecommerce/data-products",
    component: _8e8f8f88,
    name: "ecommerce-data-products___en"
  }, {
    path: "/ecommerce/order-detail",
    component: _57d8ca14,
    name: "ecommerce-order-detail___en"
  }, {
    path: "/ecommerce/orders",
    component: _14ff50e8,
    name: "ecommerce-orders___en"
  }, {
    path: "/ecommerce/product-create",
    component: _20824404,
    name: "ecommerce-product-create___en"
  }, {
    path: "/ecommerce/products",
    component: _03f59f6a,
    name: "ecommerce-products___en"
  }, {
    path: "/ecommerce/products-grid",
    component: _2de97edb,
    name: "ecommerce-products-grid___en"
  }, {
    path: "/ecommerce/sellers",
    component: _1a511bc0,
    name: "ecommerce-sellers___en"
  }, {
    path: "/email/data-inbox",
    component: _2f7b83f8,
    name: "email-data-inbox___en"
  }, {
    path: "/email/inbox",
    component: _fc5658a4,
    name: "email-inbox___en"
  }, {
    path: "/email/sidepanel",
    component: _360ab8b5,
    name: "email-sidepanel___en"
  }, {
    path: "/email/templates",
    component: _a4a0ca3e,
    name: "email-templates___en"
  }, {
    path: "/email/toolbar",
    component: _5670d3ba,
    name: "email-toolbar___en"
  }, {
    path: "/es/widgets",
    component: _1d2012e6,
    name: "widgets___es"
  }, {
    path: "/extended/rangeslider",
    component: _d4b4bb86,
    name: "extended-rangeslider___en"
  }, {
    path: "/extended/scrollspy",
    component: _d5aec224,
    name: "extended-scrollspy___en"
  }, {
    path: "/extended/sweet-alert",
    component: _1070dcc4,
    name: "extended-sweet-alert___en"
  }, {
    path: "/extended/tour",
    component: _344736ee,
    name: "extended-tour___en"
  }, {
    path: "/extras/404",
    component: _d9e0a0fe,
    name: "extras-404___en"
  }, {
    path: "/extras/404-alt",
    component: _4f84735d,
    name: "extras-404-alt___en"
  }, {
    path: "/extras/500",
    component: _7084e684,
    name: "extras-500___en"
  }, {
    path: "/extras/coming-soon",
    component: _73ced290,
    name: "extras-coming-soon___en"
  }, {
    path: "/extras/faqs",
    component: _b694cab8,
    name: "extras-faqs___en"
  }, {
    path: "/extras/invoice",
    component: _35483314,
    name: "extras-invoice___en"
  }, {
    path: "/extras/lightbox",
    component: _254a2008,
    name: "extras-lightbox___en"
  }, {
    path: "/extras/maintenance",
    component: _a9bd9a48,
    name: "extras-maintenance___en"
  }, {
    path: "/extras/pricing",
    component: _759c4e8f,
    name: "extras-pricing___en"
  }, {
    path: "/extras/search-results",
    component: _781ca698,
    name: "extras-search-results___en"
  }, {
    path: "/extras/sitemap",
    component: _eb5d6804,
    name: "extras-sitemap___en"
  }, {
    path: "/extras/starter",
    component: _6fe13a50,
    name: "extras-starter___en"
  }, {
    path: "/extras/timeline",
    component: _58551548,
    name: "extras-timeline___en"
  }, {
    path: "/forms/advanced",
    component: _4550e477,
    name: "forms-advanced___en"
  }, {
    path: "/forms/elements",
    component: _7ef7cacc,
    name: "forms-elements___en"
  }, {
    path: "/forms/file-uploads",
    component: _53b87d96,
    name: "forms-file-uploads___en"
  }, {
    path: "/forms/mask",
    component: _605e167e,
    name: "forms-mask___en"
  }, {
    path: "/forms/quill",
    component: _e6133500,
    name: "forms-quill___en"
  }, {
    path: "/forms/validation",
    component: _242b060e,
    name: "forms-validation___en"
  }, {
    path: "/forms/wizard",
    component: _f502ff00,
    name: "forms-wizard___en"
  }, {
    path: "/fr/widgets",
    component: _1d2012e6,
    name: "widgets___fr"
  }, {
    path: "/icons/boxicons",
    component: _e6830e0e,
    name: "icons-boxicons___en"
  }, {
    path: "/icons/data-fontawesome",
    component: _b88bc258,
    name: "icons-data-fontawesome___en"
  }, {
    path: "/icons/data-material",
    component: _509a527f,
    name: "icons-data-material___en"
  }, {
    path: "/icons/data-remix",
    component: _d6c0dd42,
    name: "icons-data-remix___en"
  }, {
    path: "/icons/feather",
    component: _4e6b8c6e,
    name: "icons-feather___en"
  }, {
    path: "/icons/font-awesome",
    component: _5f304ca2,
    name: "icons-font-awesome___en"
  }, {
    path: "/icons/mdi",
    component: _2398ae58,
    name: "icons-mdi___en"
  }, {
    path: "/icons/remix",
    component: _25a0e0ef,
    name: "icons-remix___en"
  }, {
    path: "/icons/weather",
    component: _880bcecc,
    name: "icons-weather___en"
  }, {
    path: "/maps/google",
    component: _4b6951e8,
    name: "maps-google___en"
  }, {
    path: "/tables/advanced",
    component: _7987d12a,
    name: "tables-advanced___en"
  }, {
    path: "/tables/basic",
    component: _7138468e,
    name: "tables-basic___en"
  }, {
    path: "/task/detail",
    component: _09f9d514,
    name: "task-detail___en"
  }, {
    path: "/task/kanban",
    component: _18a71adf,
    name: "task-kanban___en"
  }, {
    path: "/task/list",
    component: _6fa21e83,
    name: "task-list___en"
  }, {
    path: "/ui/avatars",
    component: _1ea51434,
    name: "ui-avatars___en"
  }, {
    path: "/ui/buttons",
    component: _c3cf240a,
    name: "ui-buttons___en"
  }, {
    path: "/ui/cards",
    component: _0e9d855d,
    name: "ui-cards___en"
  }, {
    path: "/ui/carousel",
    component: _200b4bd6,
    name: "ui-carousel___en"
  }, {
    path: "/ui/dropdowns",
    component: _61041808,
    name: "ui-dropdowns___en"
  }, {
    path: "/ui/general",
    component: _3a4dabe2,
    name: "ui-general___en"
  }, {
    path: "/ui/grid",
    component: _8e129c88,
    name: "ui-grid___en"
  }, {
    path: "/ui/images",
    component: _1687806e,
    name: "ui-images___en"
  }, {
    path: "/ui/list-group",
    component: _556d9f86,
    name: "ui-list-group___en"
  }, {
    path: "/ui/modals",
    component: _1666325c,
    name: "ui-modals___en"
  }, {
    path: "/ui/notifications",
    component: _0b46333c,
    name: "ui-notifications___en"
  }, {
    path: "/ui/portlets",
    component: _1c6227af,
    name: "ui-portlets___en"
  }, {
    path: "/ui/progress",
    component: _376703ba,
    name: "ui-progress___en"
  }, {
    path: "/ui/ribbons",
    component: _83655252,
    name: "ui-ribbons___en"
  }, {
    path: "/ui/spinners",
    component: _f6f64220,
    name: "ui-spinners___en"
  }, {
    path: "/ui/tabs-accordions",
    component: _27940c58,
    name: "ui-tabs-accordions___en"
  }, {
    path: "/ui/tooltips-popovers",
    component: _3ca9cc76,
    name: "ui-tooltips-popovers___en"
  }, {
    path: "/ui/typography",
    component: _3dd660a5,
    name: "ui-typography___en"
  }, {
    path: "/ui/video",
    component: _6ba06675,
    name: "ui-video___en"
  }, {
    path: "/widgets/data",
    component: _598432f0,
    name: "widgets-data___en"
  }, {
    path: "/apps/calendar/data-calendar",
    component: _0980eb07,
    name: "apps-calendar-data-calendar___en"
  }, {
    path: "/apps/chat/data",
    component: _40288a56,
    name: "apps-chat-data___en"
  }, {
    path: "/apps/companies/data",
    component: _3ab0e5d9,
    name: "apps-companies-data___en"
  }, {
    path: "/apps/tickets/data",
    component: _a1b7a236,
    name: "apps-tickets-data___en"
  }, {
    path: "/ar/account/forgot-password",
    component: _3aaae204,
    name: "account-forgot-password___ar"
  }, {
    path: "/ar/account/login",
    component: _f1dd20bc,
    name: "account-login___ar"
  }, {
    path: "/ar/account/register",
    component: _7742240c,
    name: "account-register___ar"
  }, {
    path: "/ar/apps/calendar",
    component: _92ff664e,
    name: "apps-calendar___ar"
  }, {
    path: "/ar/apps/chat",
    component: _7f47e71a,
    name: "apps-chat___ar"
  }, {
    path: "/ar/apps/companies",
    component: _3a3b9336,
    name: "apps-companies___ar"
  }, {
    path: "/ar/apps/file-manager",
    component: _966a9e18,
    name: "apps-file-manager___ar"
  }, {
    path: "/ar/apps/tickets",
    component: _5f00c942,
    name: "apps-tickets___ar"
  }, {
    path: "/ar/auth/confirm-mail",
    component: _53d918c6,
    name: "auth-confirm-mail___ar"
  }, {
    path: "/ar/auth/confirm-mail-2",
    component: _873a1f2a,
    name: "auth-confirm-mail-2___ar"
  }, {
    path: "/ar/auth/lock-screen",
    component: _6b70b21c,
    name: "auth-lock-screen___ar"
  }, {
    path: "/ar/auth/lock-screen-2",
    component: _4c798c41,
    name: "auth-lock-screen-2___ar"
  }, {
    path: "/ar/auth/login",
    component: _dcf02592,
    name: "auth-login___ar"
  }, {
    path: "/ar/auth/login-2",
    component: _49ae6c9c,
    name: "auth-login-2___ar"
  }, {
    path: "/ar/auth/logout",
    component: _26f27ba8,
    name: "auth-logout___ar"
  }, {
    path: "/ar/auth/logout-2",
    component: _3f684f5e,
    name: "auth-logout-2___ar"
  }, {
    path: "/ar/auth/recoverpwd",
    component: _6733737b,
    name: "auth-recoverpwd___ar"
  }, {
    path: "/ar/auth/recoverpwd-2",
    component: _629171e0,
    name: "auth-recoverpwd-2___ar"
  }, {
    path: "/ar/auth/register",
    component: _573f0c45,
    name: "auth-register___ar"
  }, {
    path: "/ar/auth/register-2",
    component: _7e1a002a,
    name: "auth-register-2___ar"
  }, {
    path: "/ar/auth/signin-signup",
    component: _301e2c71,
    name: "auth-signin-signup___ar"
  }, {
    path: "/ar/auth/signin-signup-2",
    component: _c89c7554,
    name: "auth-signin-signup-2___ar"
  }, {
    path: "/ar/charts/apex",
    component: _4207acba,
    name: "charts-apex___ar"
  }, {
    path: "/ar/charts/c3",
    component: _17c19188,
    name: "charts-c3___ar"
  }, {
    path: "/ar/charts/chartist",
    component: _0ef1f484,
    name: "charts-chartist___ar"
  }, {
    path: "/ar/charts/chartjs",
    component: _5d232836,
    name: "charts-chartjs___ar"
  }, {
    path: "/ar/charts/knob",
    component: _41c0d26a,
    name: "charts-knob___ar"
  }, {
    path: "/ar/contacts/list",
    component: _463dfc16,
    name: "contacts-list___ar"
  }, {
    path: "/ar/contacts/profile",
    component: _13a254bc,
    name: "contacts-profile___ar"
  }, {
    path: "/ar/dashboard/analytics",
    component: _3b7c6bae,
    name: "dashboard-analytics___ar"
  }, {
    path: "/ar/dashboard/crm",
    component: _1aaa8881,
    name: "dashboard-crm___ar"
  }, {
    path: "/ar/dashboard/sales",
    component: _37d8e7a2,
    name: "dashboard-sales___ar"
  }, {
    path: "/ar/ecommerce/cart",
    component: _0ec3d184,
    name: "ecommerce-cart___ar"
  }, {
    path: "/ar/ecommerce/checkout",
    component: _c20f4aac,
    name: "ecommerce-checkout___ar"
  }, {
    path: "/ar/ecommerce/customers",
    component: _86671c38,
    name: "ecommerce-customers___ar"
  }, {
    path: "/ar/ecommerce/data-products",
    component: _8e8f8f88,
    name: "ecommerce-data-products___ar"
  }, {
    path: "/ar/ecommerce/order-detail",
    component: _57d8ca14,
    name: "ecommerce-order-detail___ar"
  }, {
    path: "/ar/ecommerce/orders",
    component: _14ff50e8,
    name: "ecommerce-orders___ar"
  }, {
    path: "/ar/ecommerce/product-create",
    component: _20824404,
    name: "ecommerce-product-create___ar"
  }, {
    path: "/ar/ecommerce/products",
    component: _03f59f6a,
    name: "ecommerce-products___ar"
  }, {
    path: "/ar/ecommerce/products-grid",
    component: _2de97edb,
    name: "ecommerce-products-grid___ar"
  }, {
    path: "/ar/ecommerce/sellers",
    component: _1a511bc0,
    name: "ecommerce-sellers___ar"
  }, {
    path: "/ar/email/data-inbox",
    component: _2f7b83f8,
    name: "email-data-inbox___ar"
  }, {
    path: "/ar/email/inbox",
    component: _fc5658a4,
    name: "email-inbox___ar"
  }, {
    path: "/ar/email/sidepanel",
    component: _360ab8b5,
    name: "email-sidepanel___ar"
  }, {
    path: "/ar/email/templates",
    component: _a4a0ca3e,
    name: "email-templates___ar"
  }, {
    path: "/ar/email/toolbar",
    component: _5670d3ba,
    name: "email-toolbar___ar"
  }, {
    path: "/ar/extended/rangeslider",
    component: _d4b4bb86,
    name: "extended-rangeslider___ar"
  }, {
    path: "/ar/extended/scrollspy",
    component: _d5aec224,
    name: "extended-scrollspy___ar"
  }, {
    path: "/ar/extended/sweet-alert",
    component: _1070dcc4,
    name: "extended-sweet-alert___ar"
  }, {
    path: "/ar/extended/tour",
    component: _344736ee,
    name: "extended-tour___ar"
  }, {
    path: "/ar/extras/404",
    component: _d9e0a0fe,
    name: "extras-404___ar"
  }, {
    path: "/ar/extras/404-alt",
    component: _4f84735d,
    name: "extras-404-alt___ar"
  }, {
    path: "/ar/extras/500",
    component: _7084e684,
    name: "extras-500___ar"
  }, {
    path: "/ar/extras/coming-soon",
    component: _73ced290,
    name: "extras-coming-soon___ar"
  }, {
    path: "/ar/extras/faqs",
    component: _b694cab8,
    name: "extras-faqs___ar"
  }, {
    path: "/ar/extras/invoice",
    component: _35483314,
    name: "extras-invoice___ar"
  }, {
    path: "/ar/extras/lightbox",
    component: _254a2008,
    name: "extras-lightbox___ar"
  }, {
    path: "/ar/extras/maintenance",
    component: _a9bd9a48,
    name: "extras-maintenance___ar"
  }, {
    path: "/ar/extras/pricing",
    component: _759c4e8f,
    name: "extras-pricing___ar"
  }, {
    path: "/ar/extras/search-results",
    component: _781ca698,
    name: "extras-search-results___ar"
  }, {
    path: "/ar/extras/sitemap",
    component: _eb5d6804,
    name: "extras-sitemap___ar"
  }, {
    path: "/ar/extras/starter",
    component: _6fe13a50,
    name: "extras-starter___ar"
  }, {
    path: "/ar/extras/timeline",
    component: _58551548,
    name: "extras-timeline___ar"
  }, {
    path: "/ar/forms/advanced",
    component: _4550e477,
    name: "forms-advanced___ar"
  }, {
    path: "/ar/forms/elements",
    component: _7ef7cacc,
    name: "forms-elements___ar"
  }, {
    path: "/ar/forms/file-uploads",
    component: _53b87d96,
    name: "forms-file-uploads___ar"
  }, {
    path: "/ar/forms/mask",
    component: _605e167e,
    name: "forms-mask___ar"
  }, {
    path: "/ar/forms/quill",
    component: _e6133500,
    name: "forms-quill___ar"
  }, {
    path: "/ar/forms/validation",
    component: _242b060e,
    name: "forms-validation___ar"
  }, {
    path: "/ar/forms/wizard",
    component: _f502ff00,
    name: "forms-wizard___ar"
  }, {
    path: "/ar/icons/boxicons",
    component: _e6830e0e,
    name: "icons-boxicons___ar"
  }, {
    path: "/ar/icons/data-fontawesome",
    component: _b88bc258,
    name: "icons-data-fontawesome___ar"
  }, {
    path: "/ar/icons/data-material",
    component: _509a527f,
    name: "icons-data-material___ar"
  }, {
    path: "/ar/icons/data-remix",
    component: _d6c0dd42,
    name: "icons-data-remix___ar"
  }, {
    path: "/ar/icons/feather",
    component: _4e6b8c6e,
    name: "icons-feather___ar"
  }, {
    path: "/ar/icons/font-awesome",
    component: _5f304ca2,
    name: "icons-font-awesome___ar"
  }, {
    path: "/ar/icons/mdi",
    component: _2398ae58,
    name: "icons-mdi___ar"
  }, {
    path: "/ar/icons/remix",
    component: _25a0e0ef,
    name: "icons-remix___ar"
  }, {
    path: "/ar/icons/weather",
    component: _880bcecc,
    name: "icons-weather___ar"
  }, {
    path: "/ar/maps/google",
    component: _4b6951e8,
    name: "maps-google___ar"
  }, {
    path: "/ar/tables/advanced",
    component: _7987d12a,
    name: "tables-advanced___ar"
  }, {
    path: "/ar/tables/basic",
    component: _7138468e,
    name: "tables-basic___ar"
  }, {
    path: "/ar/task/detail",
    component: _09f9d514,
    name: "task-detail___ar"
  }, {
    path: "/ar/task/kanban",
    component: _18a71adf,
    name: "task-kanban___ar"
  }, {
    path: "/ar/task/list",
    component: _6fa21e83,
    name: "task-list___ar"
  }, {
    path: "/ar/ui/avatars",
    component: _1ea51434,
    name: "ui-avatars___ar"
  }, {
    path: "/ar/ui/buttons",
    component: _c3cf240a,
    name: "ui-buttons___ar"
  }, {
    path: "/ar/ui/cards",
    component: _0e9d855d,
    name: "ui-cards___ar"
  }, {
    path: "/ar/ui/carousel",
    component: _200b4bd6,
    name: "ui-carousel___ar"
  }, {
    path: "/ar/ui/dropdowns",
    component: _61041808,
    name: "ui-dropdowns___ar"
  }, {
    path: "/ar/ui/general",
    component: _3a4dabe2,
    name: "ui-general___ar"
  }, {
    path: "/ar/ui/grid",
    component: _8e129c88,
    name: "ui-grid___ar"
  }, {
    path: "/ar/ui/images",
    component: _1687806e,
    name: "ui-images___ar"
  }, {
    path: "/ar/ui/list-group",
    component: _556d9f86,
    name: "ui-list-group___ar"
  }, {
    path: "/ar/ui/modals",
    component: _1666325c,
    name: "ui-modals___ar"
  }, {
    path: "/ar/ui/notifications",
    component: _0b46333c,
    name: "ui-notifications___ar"
  }, {
    path: "/ar/ui/portlets",
    component: _1c6227af,
    name: "ui-portlets___ar"
  }, {
    path: "/ar/ui/progress",
    component: _376703ba,
    name: "ui-progress___ar"
  }, {
    path: "/ar/ui/ribbons",
    component: _83655252,
    name: "ui-ribbons___ar"
  }, {
    path: "/ar/ui/spinners",
    component: _f6f64220,
    name: "ui-spinners___ar"
  }, {
    path: "/ar/ui/tabs-accordions",
    component: _27940c58,
    name: "ui-tabs-accordions___ar"
  }, {
    path: "/ar/ui/tooltips-popovers",
    component: _3ca9cc76,
    name: "ui-tooltips-popovers___ar"
  }, {
    path: "/ar/ui/typography",
    component: _3dd660a5,
    name: "ui-typography___ar"
  }, {
    path: "/ar/ui/video",
    component: _6ba06675,
    name: "ui-video___ar"
  }, {
    path: "/ar/widgets/data",
    component: _598432f0,
    name: "widgets-data___ar"
  }, {
    path: "/charts/apex/data",
    component: _22fd905d,
    name: "charts-apex-data___en"
  }, {
    path: "/charts/c3/data",
    component: _e0335eaa,
    name: "charts-c3-data___en"
  }, {
    path: "/charts/chartist/data",
    component: _1c8b42a7,
    name: "charts-chartist-data___en"
  }, {
    path: "/charts/chartjs/BarChart",
    component: _961f6d30,
    name: "charts-chartjs-BarChart___en"
  }, {
    path: "/charts/chartjs/DonutChart",
    component: _ebb54c0e,
    name: "charts-chartjs-DonutChart___en"
  }, {
    path: "/charts/chartjs/LineChart",
    component: _7c3cd1bd,
    name: "charts-chartjs-LineChart___en"
  }, {
    path: "/charts/chartjs/PieChart",
    component: _60122c0f,
    name: "charts-chartjs-PieChart___en"
  }, {
    path: "/charts/chartjs/PolarChart",
    component: _f292ad46,
    name: "charts-chartjs-PolarChart___en"
  }, {
    path: "/charts/chartjs/RadarChart",
    component: _01bab695,
    name: "charts-chartjs-RadarChart___en"
  }, {
    path: "/dashboard/analytics/channels",
    component: _9d1d8b6e,
    name: "dashboard-analytics-channels___en"
  }, {
    path: "/dashboard/analytics/overview",
    component: _5b670772,
    name: "dashboard-analytics-overview___en"
  }, {
    path: "/dashboard/analytics/social-media",
    component: _0ab5d97d,
    name: "dashboard-analytics-social-media___en"
  }, {
    path: "/dashboard/analytics/sources",
    component: _43d8664f,
    name: "dashboard-analytics-sources___en"
  }, {
    path: "/dashboard/analytics/users",
    component: _27aba45f,
    name: "dashboard-analytics-users___en"
  }, {
    path: "/ecommerce/customers/data",
    component: _27a59807,
    name: "ecommerce-customers-data___en"
  }, {
    path: "/ecommerce/orders/data",
    component: _6be6c7af,
    name: "ecommerce-orders-data___en"
  }, {
    path: "/ecommerce/products/data",
    component: _70f8c42e,
    name: "ecommerce-products-data___en"
  }, {
    path: "/es/account/forgot-password",
    component: _3aaae204,
    name: "account-forgot-password___es"
  }, {
    path: "/es/account/login",
    component: _f1dd20bc,
    name: "account-login___es"
  }, {
    path: "/es/account/register",
    component: _7742240c,
    name: "account-register___es"
  }, {
    path: "/es/apps/calendar",
    component: _92ff664e,
    name: "apps-calendar___es"
  }, {
    path: "/es/apps/chat",
    component: _7f47e71a,
    name: "apps-chat___es"
  }, {
    path: "/es/apps/companies",
    component: _3a3b9336,
    name: "apps-companies___es"
  }, {
    path: "/es/apps/file-manager",
    component: _966a9e18,
    name: "apps-file-manager___es"
  }, {
    path: "/es/apps/tickets",
    component: _5f00c942,
    name: "apps-tickets___es"
  }, {
    path: "/es/auth/confirm-mail",
    component: _53d918c6,
    name: "auth-confirm-mail___es"
  }, {
    path: "/es/auth/confirm-mail-2",
    component: _873a1f2a,
    name: "auth-confirm-mail-2___es"
  }, {
    path: "/es/auth/lock-screen",
    component: _6b70b21c,
    name: "auth-lock-screen___es"
  }, {
    path: "/es/auth/lock-screen-2",
    component: _4c798c41,
    name: "auth-lock-screen-2___es"
  }, {
    path: "/es/auth/login",
    component: _dcf02592,
    name: "auth-login___es"
  }, {
    path: "/es/auth/login-2",
    component: _49ae6c9c,
    name: "auth-login-2___es"
  }, {
    path: "/es/auth/logout",
    component: _26f27ba8,
    name: "auth-logout___es"
  }, {
    path: "/es/auth/logout-2",
    component: _3f684f5e,
    name: "auth-logout-2___es"
  }, {
    path: "/es/auth/recoverpwd",
    component: _6733737b,
    name: "auth-recoverpwd___es"
  }, {
    path: "/es/auth/recoverpwd-2",
    component: _629171e0,
    name: "auth-recoverpwd-2___es"
  }, {
    path: "/es/auth/register",
    component: _573f0c45,
    name: "auth-register___es"
  }, {
    path: "/es/auth/register-2",
    component: _7e1a002a,
    name: "auth-register-2___es"
  }, {
    path: "/es/auth/signin-signup",
    component: _301e2c71,
    name: "auth-signin-signup___es"
  }, {
    path: "/es/auth/signin-signup-2",
    component: _c89c7554,
    name: "auth-signin-signup-2___es"
  }, {
    path: "/es/charts/apex",
    component: _4207acba,
    name: "charts-apex___es"
  }, {
    path: "/es/charts/c3",
    component: _17c19188,
    name: "charts-c3___es"
  }, {
    path: "/es/charts/chartist",
    component: _0ef1f484,
    name: "charts-chartist___es"
  }, {
    path: "/es/charts/chartjs",
    component: _5d232836,
    name: "charts-chartjs___es"
  }, {
    path: "/es/charts/knob",
    component: _41c0d26a,
    name: "charts-knob___es"
  }, {
    path: "/es/contacts/list",
    component: _463dfc16,
    name: "contacts-list___es"
  }, {
    path: "/es/contacts/profile",
    component: _13a254bc,
    name: "contacts-profile___es"
  }, {
    path: "/es/dashboard/analytics",
    component: _3b7c6bae,
    name: "dashboard-analytics___es"
  }, {
    path: "/es/dashboard/crm",
    component: _1aaa8881,
    name: "dashboard-crm___es"
  }, {
    path: "/es/dashboard/sales",
    component: _37d8e7a2,
    name: "dashboard-sales___es"
  }, {
    path: "/es/ecommerce/cart",
    component: _0ec3d184,
    name: "ecommerce-cart___es"
  }, {
    path: "/es/ecommerce/checkout",
    component: _c20f4aac,
    name: "ecommerce-checkout___es"
  }, {
    path: "/es/ecommerce/customers",
    component: _86671c38,
    name: "ecommerce-customers___es"
  }, {
    path: "/es/ecommerce/data-products",
    component: _8e8f8f88,
    name: "ecommerce-data-products___es"
  }, {
    path: "/es/ecommerce/order-detail",
    component: _57d8ca14,
    name: "ecommerce-order-detail___es"
  }, {
    path: "/es/ecommerce/orders",
    component: _14ff50e8,
    name: "ecommerce-orders___es"
  }, {
    path: "/es/ecommerce/product-create",
    component: _20824404,
    name: "ecommerce-product-create___es"
  }, {
    path: "/es/ecommerce/products",
    component: _03f59f6a,
    name: "ecommerce-products___es"
  }, {
    path: "/es/ecommerce/products-grid",
    component: _2de97edb,
    name: "ecommerce-products-grid___es"
  }, {
    path: "/es/ecommerce/sellers",
    component: _1a511bc0,
    name: "ecommerce-sellers___es"
  }, {
    path: "/es/email/data-inbox",
    component: _2f7b83f8,
    name: "email-data-inbox___es"
  }, {
    path: "/es/email/inbox",
    component: _fc5658a4,
    name: "email-inbox___es"
  }, {
    path: "/es/email/sidepanel",
    component: _360ab8b5,
    name: "email-sidepanel___es"
  }, {
    path: "/es/email/templates",
    component: _a4a0ca3e,
    name: "email-templates___es"
  }, {
    path: "/es/email/toolbar",
    component: _5670d3ba,
    name: "email-toolbar___es"
  }, {
    path: "/es/extended/rangeslider",
    component: _d4b4bb86,
    name: "extended-rangeslider___es"
  }, {
    path: "/es/extended/scrollspy",
    component: _d5aec224,
    name: "extended-scrollspy___es"
  }, {
    path: "/es/extended/sweet-alert",
    component: _1070dcc4,
    name: "extended-sweet-alert___es"
  }, {
    path: "/es/extended/tour",
    component: _344736ee,
    name: "extended-tour___es"
  }, {
    path: "/es/extras/404",
    component: _d9e0a0fe,
    name: "extras-404___es"
  }, {
    path: "/es/extras/404-alt",
    component: _4f84735d,
    name: "extras-404-alt___es"
  }, {
    path: "/es/extras/500",
    component: _7084e684,
    name: "extras-500___es"
  }, {
    path: "/es/extras/coming-soon",
    component: _73ced290,
    name: "extras-coming-soon___es"
  }, {
    path: "/es/extras/faqs",
    component: _b694cab8,
    name: "extras-faqs___es"
  }, {
    path: "/es/extras/invoice",
    component: _35483314,
    name: "extras-invoice___es"
  }, {
    path: "/es/extras/lightbox",
    component: _254a2008,
    name: "extras-lightbox___es"
  }, {
    path: "/es/extras/maintenance",
    component: _a9bd9a48,
    name: "extras-maintenance___es"
  }, {
    path: "/es/extras/pricing",
    component: _759c4e8f,
    name: "extras-pricing___es"
  }, {
    path: "/es/extras/search-results",
    component: _781ca698,
    name: "extras-search-results___es"
  }, {
    path: "/es/extras/sitemap",
    component: _eb5d6804,
    name: "extras-sitemap___es"
  }, {
    path: "/es/extras/starter",
    component: _6fe13a50,
    name: "extras-starter___es"
  }, {
    path: "/es/extras/timeline",
    component: _58551548,
    name: "extras-timeline___es"
  }, {
    path: "/es/forms/advanced",
    component: _4550e477,
    name: "forms-advanced___es"
  }, {
    path: "/es/forms/elements",
    component: _7ef7cacc,
    name: "forms-elements___es"
  }, {
    path: "/es/forms/file-uploads",
    component: _53b87d96,
    name: "forms-file-uploads___es"
  }, {
    path: "/es/forms/mask",
    component: _605e167e,
    name: "forms-mask___es"
  }, {
    path: "/es/forms/quill",
    component: _e6133500,
    name: "forms-quill___es"
  }, {
    path: "/es/forms/validation",
    component: _242b060e,
    name: "forms-validation___es"
  }, {
    path: "/es/forms/wizard",
    component: _f502ff00,
    name: "forms-wizard___es"
  }, {
    path: "/es/icons/boxicons",
    component: _e6830e0e,
    name: "icons-boxicons___es"
  }, {
    path: "/es/icons/data-fontawesome",
    component: _b88bc258,
    name: "icons-data-fontawesome___es"
  }, {
    path: "/es/icons/data-material",
    component: _509a527f,
    name: "icons-data-material___es"
  }, {
    path: "/es/icons/data-remix",
    component: _d6c0dd42,
    name: "icons-data-remix___es"
  }, {
    path: "/es/icons/feather",
    component: _4e6b8c6e,
    name: "icons-feather___es"
  }, {
    path: "/es/icons/font-awesome",
    component: _5f304ca2,
    name: "icons-font-awesome___es"
  }, {
    path: "/es/icons/mdi",
    component: _2398ae58,
    name: "icons-mdi___es"
  }, {
    path: "/es/icons/remix",
    component: _25a0e0ef,
    name: "icons-remix___es"
  }, {
    path: "/es/icons/weather",
    component: _880bcecc,
    name: "icons-weather___es"
  }, {
    path: "/es/maps/google",
    component: _4b6951e8,
    name: "maps-google___es"
  }, {
    path: "/es/tables/advanced",
    component: _7987d12a,
    name: "tables-advanced___es"
  }, {
    path: "/es/tables/basic",
    component: _7138468e,
    name: "tables-basic___es"
  }, {
    path: "/es/task/detail",
    component: _09f9d514,
    name: "task-detail___es"
  }, {
    path: "/es/task/kanban",
    component: _18a71adf,
    name: "task-kanban___es"
  }, {
    path: "/es/task/list",
    component: _6fa21e83,
    name: "task-list___es"
  }, {
    path: "/es/ui/avatars",
    component: _1ea51434,
    name: "ui-avatars___es"
  }, {
    path: "/es/ui/buttons",
    component: _c3cf240a,
    name: "ui-buttons___es"
  }, {
    path: "/es/ui/cards",
    component: _0e9d855d,
    name: "ui-cards___es"
  }, {
    path: "/es/ui/carousel",
    component: _200b4bd6,
    name: "ui-carousel___es"
  }, {
    path: "/es/ui/dropdowns",
    component: _61041808,
    name: "ui-dropdowns___es"
  }, {
    path: "/es/ui/general",
    component: _3a4dabe2,
    name: "ui-general___es"
  }, {
    path: "/es/ui/grid",
    component: _8e129c88,
    name: "ui-grid___es"
  }, {
    path: "/es/ui/images",
    component: _1687806e,
    name: "ui-images___es"
  }, {
    path: "/es/ui/list-group",
    component: _556d9f86,
    name: "ui-list-group___es"
  }, {
    path: "/es/ui/modals",
    component: _1666325c,
    name: "ui-modals___es"
  }, {
    path: "/es/ui/notifications",
    component: _0b46333c,
    name: "ui-notifications___es"
  }, {
    path: "/es/ui/portlets",
    component: _1c6227af,
    name: "ui-portlets___es"
  }, {
    path: "/es/ui/progress",
    component: _376703ba,
    name: "ui-progress___es"
  }, {
    path: "/es/ui/ribbons",
    component: _83655252,
    name: "ui-ribbons___es"
  }, {
    path: "/es/ui/spinners",
    component: _f6f64220,
    name: "ui-spinners___es"
  }, {
    path: "/es/ui/tabs-accordions",
    component: _27940c58,
    name: "ui-tabs-accordions___es"
  }, {
    path: "/es/ui/tooltips-popovers",
    component: _3ca9cc76,
    name: "ui-tooltips-popovers___es"
  }, {
    path: "/es/ui/typography",
    component: _3dd660a5,
    name: "ui-typography___es"
  }, {
    path: "/es/ui/video",
    component: _6ba06675,
    name: "ui-video___es"
  }, {
    path: "/es/widgets/data",
    component: _598432f0,
    name: "widgets-data___es"
  }, {
    path: "/fr/account/forgot-password",
    component: _3aaae204,
    name: "account-forgot-password___fr"
  }, {
    path: "/fr/account/login",
    component: _f1dd20bc,
    name: "account-login___fr"
  }, {
    path: "/fr/account/register",
    component: _7742240c,
    name: "account-register___fr"
  }, {
    path: "/fr/apps/calendar",
    component: _92ff664e,
    name: "apps-calendar___fr"
  }, {
    path: "/fr/apps/chat",
    component: _7f47e71a,
    name: "apps-chat___fr"
  }, {
    path: "/fr/apps/companies",
    component: _3a3b9336,
    name: "apps-companies___fr"
  }, {
    path: "/fr/apps/file-manager",
    component: _966a9e18,
    name: "apps-file-manager___fr"
  }, {
    path: "/fr/apps/tickets",
    component: _5f00c942,
    name: "apps-tickets___fr"
  }, {
    path: "/fr/auth/confirm-mail",
    component: _53d918c6,
    name: "auth-confirm-mail___fr"
  }, {
    path: "/fr/auth/confirm-mail-2",
    component: _873a1f2a,
    name: "auth-confirm-mail-2___fr"
  }, {
    path: "/fr/auth/lock-screen",
    component: _6b70b21c,
    name: "auth-lock-screen___fr"
  }, {
    path: "/fr/auth/lock-screen-2",
    component: _4c798c41,
    name: "auth-lock-screen-2___fr"
  }, {
    path: "/fr/auth/login",
    component: _dcf02592,
    name: "auth-login___fr"
  }, {
    path: "/fr/auth/login-2",
    component: _49ae6c9c,
    name: "auth-login-2___fr"
  }, {
    path: "/fr/auth/logout",
    component: _26f27ba8,
    name: "auth-logout___fr"
  }, {
    path: "/fr/auth/logout-2",
    component: _3f684f5e,
    name: "auth-logout-2___fr"
  }, {
    path: "/fr/auth/recoverpwd",
    component: _6733737b,
    name: "auth-recoverpwd___fr"
  }, {
    path: "/fr/auth/recoverpwd-2",
    component: _629171e0,
    name: "auth-recoverpwd-2___fr"
  }, {
    path: "/fr/auth/register",
    component: _573f0c45,
    name: "auth-register___fr"
  }, {
    path: "/fr/auth/register-2",
    component: _7e1a002a,
    name: "auth-register-2___fr"
  }, {
    path: "/fr/auth/signin-signup",
    component: _301e2c71,
    name: "auth-signin-signup___fr"
  }, {
    path: "/fr/auth/signin-signup-2",
    component: _c89c7554,
    name: "auth-signin-signup-2___fr"
  }, {
    path: "/fr/charts/apex",
    component: _4207acba,
    name: "charts-apex___fr"
  }, {
    path: "/fr/charts/c3",
    component: _17c19188,
    name: "charts-c3___fr"
  }, {
    path: "/fr/charts/chartist",
    component: _0ef1f484,
    name: "charts-chartist___fr"
  }, {
    path: "/fr/charts/chartjs",
    component: _5d232836,
    name: "charts-chartjs___fr"
  }, {
    path: "/fr/charts/knob",
    component: _41c0d26a,
    name: "charts-knob___fr"
  }, {
    path: "/fr/contacts/list",
    component: _463dfc16,
    name: "contacts-list___fr"
  }, {
    path: "/fr/contacts/profile",
    component: _13a254bc,
    name: "contacts-profile___fr"
  }, {
    path: "/fr/dashboard/analytics",
    component: _3b7c6bae,
    name: "dashboard-analytics___fr"
  }, {
    path: "/fr/dashboard/crm",
    component: _1aaa8881,
    name: "dashboard-crm___fr"
  }, {
    path: "/fr/dashboard/sales",
    component: _37d8e7a2,
    name: "dashboard-sales___fr"
  }, {
    path: "/fr/ecommerce/cart",
    component: _0ec3d184,
    name: "ecommerce-cart___fr"
  }, {
    path: "/fr/ecommerce/checkout",
    component: _c20f4aac,
    name: "ecommerce-checkout___fr"
  }, {
    path: "/fr/ecommerce/customers",
    component: _86671c38,
    name: "ecommerce-customers___fr"
  }, {
    path: "/fr/ecommerce/data-products",
    component: _8e8f8f88,
    name: "ecommerce-data-products___fr"
  }, {
    path: "/fr/ecommerce/order-detail",
    component: _57d8ca14,
    name: "ecommerce-order-detail___fr"
  }, {
    path: "/fr/ecommerce/orders",
    component: _14ff50e8,
    name: "ecommerce-orders___fr"
  }, {
    path: "/fr/ecommerce/product-create",
    component: _20824404,
    name: "ecommerce-product-create___fr"
  }, {
    path: "/fr/ecommerce/products",
    component: _03f59f6a,
    name: "ecommerce-products___fr"
  }, {
    path: "/fr/ecommerce/products-grid",
    component: _2de97edb,
    name: "ecommerce-products-grid___fr"
  }, {
    path: "/fr/ecommerce/sellers",
    component: _1a511bc0,
    name: "ecommerce-sellers___fr"
  }, {
    path: "/fr/email/data-inbox",
    component: _2f7b83f8,
    name: "email-data-inbox___fr"
  }, {
    path: "/fr/email/inbox",
    component: _fc5658a4,
    name: "email-inbox___fr"
  }, {
    path: "/fr/email/sidepanel",
    component: _360ab8b5,
    name: "email-sidepanel___fr"
  }, {
    path: "/fr/email/templates",
    component: _a4a0ca3e,
    name: "email-templates___fr"
  }, {
    path: "/fr/email/toolbar",
    component: _5670d3ba,
    name: "email-toolbar___fr"
  }, {
    path: "/fr/extended/rangeslider",
    component: _d4b4bb86,
    name: "extended-rangeslider___fr"
  }, {
    path: "/fr/extended/scrollspy",
    component: _d5aec224,
    name: "extended-scrollspy___fr"
  }, {
    path: "/fr/extended/sweet-alert",
    component: _1070dcc4,
    name: "extended-sweet-alert___fr"
  }, {
    path: "/fr/extended/tour",
    component: _344736ee,
    name: "extended-tour___fr"
  }, {
    path: "/fr/extras/404",
    component: _d9e0a0fe,
    name: "extras-404___fr"
  }, {
    path: "/fr/extras/404-alt",
    component: _4f84735d,
    name: "extras-404-alt___fr"
  }, {
    path: "/fr/extras/500",
    component: _7084e684,
    name: "extras-500___fr"
  }, {
    path: "/fr/extras/coming-soon",
    component: _73ced290,
    name: "extras-coming-soon___fr"
  }, {
    path: "/fr/extras/faqs",
    component: _b694cab8,
    name: "extras-faqs___fr"
  }, {
    path: "/fr/extras/invoice",
    component: _35483314,
    name: "extras-invoice___fr"
  }, {
    path: "/fr/extras/lightbox",
    component: _254a2008,
    name: "extras-lightbox___fr"
  }, {
    path: "/fr/extras/maintenance",
    component: _a9bd9a48,
    name: "extras-maintenance___fr"
  }, {
    path: "/fr/extras/pricing",
    component: _759c4e8f,
    name: "extras-pricing___fr"
  }, {
    path: "/fr/extras/search-results",
    component: _781ca698,
    name: "extras-search-results___fr"
  }, {
    path: "/fr/extras/sitemap",
    component: _eb5d6804,
    name: "extras-sitemap___fr"
  }, {
    path: "/fr/extras/starter",
    component: _6fe13a50,
    name: "extras-starter___fr"
  }, {
    path: "/fr/extras/timeline",
    component: _58551548,
    name: "extras-timeline___fr"
  }, {
    path: "/fr/forms/advanced",
    component: _4550e477,
    name: "forms-advanced___fr"
  }, {
    path: "/fr/forms/elements",
    component: _7ef7cacc,
    name: "forms-elements___fr"
  }, {
    path: "/fr/forms/file-uploads",
    component: _53b87d96,
    name: "forms-file-uploads___fr"
  }, {
    path: "/fr/forms/mask",
    component: _605e167e,
    name: "forms-mask___fr"
  }, {
    path: "/fr/forms/quill",
    component: _e6133500,
    name: "forms-quill___fr"
  }, {
    path: "/fr/forms/validation",
    component: _242b060e,
    name: "forms-validation___fr"
  }, {
    path: "/fr/forms/wizard",
    component: _f502ff00,
    name: "forms-wizard___fr"
  }, {
    path: "/fr/icons/boxicons",
    component: _e6830e0e,
    name: "icons-boxicons___fr"
  }, {
    path: "/fr/icons/data-fontawesome",
    component: _b88bc258,
    name: "icons-data-fontawesome___fr"
  }, {
    path: "/fr/icons/data-material",
    component: _509a527f,
    name: "icons-data-material___fr"
  }, {
    path: "/fr/icons/data-remix",
    component: _d6c0dd42,
    name: "icons-data-remix___fr"
  }, {
    path: "/fr/icons/feather",
    component: _4e6b8c6e,
    name: "icons-feather___fr"
  }, {
    path: "/fr/icons/font-awesome",
    component: _5f304ca2,
    name: "icons-font-awesome___fr"
  }, {
    path: "/fr/icons/mdi",
    component: _2398ae58,
    name: "icons-mdi___fr"
  }, {
    path: "/fr/icons/remix",
    component: _25a0e0ef,
    name: "icons-remix___fr"
  }, {
    path: "/fr/icons/weather",
    component: _880bcecc,
    name: "icons-weather___fr"
  }, {
    path: "/fr/maps/google",
    component: _4b6951e8,
    name: "maps-google___fr"
  }, {
    path: "/fr/tables/advanced",
    component: _7987d12a,
    name: "tables-advanced___fr"
  }, {
    path: "/fr/tables/basic",
    component: _7138468e,
    name: "tables-basic___fr"
  }, {
    path: "/fr/task/detail",
    component: _09f9d514,
    name: "task-detail___fr"
  }, {
    path: "/fr/task/kanban",
    component: _18a71adf,
    name: "task-kanban___fr"
  }, {
    path: "/fr/task/list",
    component: _6fa21e83,
    name: "task-list___fr"
  }, {
    path: "/fr/ui/avatars",
    component: _1ea51434,
    name: "ui-avatars___fr"
  }, {
    path: "/fr/ui/buttons",
    component: _c3cf240a,
    name: "ui-buttons___fr"
  }, {
    path: "/fr/ui/cards",
    component: _0e9d855d,
    name: "ui-cards___fr"
  }, {
    path: "/fr/ui/carousel",
    component: _200b4bd6,
    name: "ui-carousel___fr"
  }, {
    path: "/fr/ui/dropdowns",
    component: _61041808,
    name: "ui-dropdowns___fr"
  }, {
    path: "/fr/ui/general",
    component: _3a4dabe2,
    name: "ui-general___fr"
  }, {
    path: "/fr/ui/grid",
    component: _8e129c88,
    name: "ui-grid___fr"
  }, {
    path: "/fr/ui/images",
    component: _1687806e,
    name: "ui-images___fr"
  }, {
    path: "/fr/ui/list-group",
    component: _556d9f86,
    name: "ui-list-group___fr"
  }, {
    path: "/fr/ui/modals",
    component: _1666325c,
    name: "ui-modals___fr"
  }, {
    path: "/fr/ui/notifications",
    component: _0b46333c,
    name: "ui-notifications___fr"
  }, {
    path: "/fr/ui/portlets",
    component: _1c6227af,
    name: "ui-portlets___fr"
  }, {
    path: "/fr/ui/progress",
    component: _376703ba,
    name: "ui-progress___fr"
  }, {
    path: "/fr/ui/ribbons",
    component: _83655252,
    name: "ui-ribbons___fr"
  }, {
    path: "/fr/ui/spinners",
    component: _f6f64220,
    name: "ui-spinners___fr"
  }, {
    path: "/fr/ui/tabs-accordions",
    component: _27940c58,
    name: "ui-tabs-accordions___fr"
  }, {
    path: "/fr/ui/tooltips-popovers",
    component: _3ca9cc76,
    name: "ui-tooltips-popovers___fr"
  }, {
    path: "/fr/ui/typography",
    component: _3dd660a5,
    name: "ui-typography___fr"
  }, {
    path: "/fr/ui/video",
    component: _6ba06675,
    name: "ui-video___fr"
  }, {
    path: "/fr/widgets/data",
    component: _598432f0,
    name: "widgets-data___fr"
  }, {
    path: "/tables/advanced/data",
    component: _281c10cd,
    name: "tables-advanced-data___en"
  }, {
    path: "/task/kanban/data",
    component: _4307787c,
    name: "task-kanban-data___en"
  }, {
    path: "/ar/apps/calendar/data-calendar",
    component: _0980eb07,
    name: "apps-calendar-data-calendar___ar"
  }, {
    path: "/ar/apps/chat/data",
    component: _40288a56,
    name: "apps-chat-data___ar"
  }, {
    path: "/ar/apps/companies/data",
    component: _3ab0e5d9,
    name: "apps-companies-data___ar"
  }, {
    path: "/ar/apps/tickets/data",
    component: _a1b7a236,
    name: "apps-tickets-data___ar"
  }, {
    path: "/ar/charts/apex/data",
    component: _22fd905d,
    name: "charts-apex-data___ar"
  }, {
    path: "/ar/charts/c3/data",
    component: _e0335eaa,
    name: "charts-c3-data___ar"
  }, {
    path: "/ar/charts/chartist/data",
    component: _1c8b42a7,
    name: "charts-chartist-data___ar"
  }, {
    path: "/ar/charts/chartjs/BarChart",
    component: _961f6d30,
    name: "charts-chartjs-BarChart___ar"
  }, {
    path: "/ar/charts/chartjs/DonutChart",
    component: _ebb54c0e,
    name: "charts-chartjs-DonutChart___ar"
  }, {
    path: "/ar/charts/chartjs/LineChart",
    component: _7c3cd1bd,
    name: "charts-chartjs-LineChart___ar"
  }, {
    path: "/ar/charts/chartjs/PieChart",
    component: _60122c0f,
    name: "charts-chartjs-PieChart___ar"
  }, {
    path: "/ar/charts/chartjs/PolarChart",
    component: _f292ad46,
    name: "charts-chartjs-PolarChart___ar"
  }, {
    path: "/ar/charts/chartjs/RadarChart",
    component: _01bab695,
    name: "charts-chartjs-RadarChart___ar"
  }, {
    path: "/ar/dashboard/analytics/channels",
    component: _9d1d8b6e,
    name: "dashboard-analytics-channels___ar"
  }, {
    path: "/ar/dashboard/analytics/overview",
    component: _5b670772,
    name: "dashboard-analytics-overview___ar"
  }, {
    path: "/ar/dashboard/analytics/social-media",
    component: _0ab5d97d,
    name: "dashboard-analytics-social-media___ar"
  }, {
    path: "/ar/dashboard/analytics/sources",
    component: _43d8664f,
    name: "dashboard-analytics-sources___ar"
  }, {
    path: "/ar/dashboard/analytics/users",
    component: _27aba45f,
    name: "dashboard-analytics-users___ar"
  }, {
    path: "/ar/ecommerce/customers/data",
    component: _27a59807,
    name: "ecommerce-customers-data___ar"
  }, {
    path: "/ar/ecommerce/orders/data",
    component: _6be6c7af,
    name: "ecommerce-orders-data___ar"
  }, {
    path: "/ar/ecommerce/products/data",
    component: _70f8c42e,
    name: "ecommerce-products-data___ar"
  }, {
    path: "/ar/tables/advanced/data",
    component: _281c10cd,
    name: "tables-advanced-data___ar"
  }, {
    path: "/ar/task/kanban/data",
    component: _4307787c,
    name: "task-kanban-data___ar"
  }, {
    path: "/es/apps/calendar/data-calendar",
    component: _0980eb07,
    name: "apps-calendar-data-calendar___es"
  }, {
    path: "/es/apps/chat/data",
    component: _40288a56,
    name: "apps-chat-data___es"
  }, {
    path: "/es/apps/companies/data",
    component: _3ab0e5d9,
    name: "apps-companies-data___es"
  }, {
    path: "/es/apps/tickets/data",
    component: _a1b7a236,
    name: "apps-tickets-data___es"
  }, {
    path: "/es/charts/apex/data",
    component: _22fd905d,
    name: "charts-apex-data___es"
  }, {
    path: "/es/charts/c3/data",
    component: _e0335eaa,
    name: "charts-c3-data___es"
  }, {
    path: "/es/charts/chartist/data",
    component: _1c8b42a7,
    name: "charts-chartist-data___es"
  }, {
    path: "/es/charts/chartjs/BarChart",
    component: _961f6d30,
    name: "charts-chartjs-BarChart___es"
  }, {
    path: "/es/charts/chartjs/DonutChart",
    component: _ebb54c0e,
    name: "charts-chartjs-DonutChart___es"
  }, {
    path: "/es/charts/chartjs/LineChart",
    component: _7c3cd1bd,
    name: "charts-chartjs-LineChart___es"
  }, {
    path: "/es/charts/chartjs/PieChart",
    component: _60122c0f,
    name: "charts-chartjs-PieChart___es"
  }, {
    path: "/es/charts/chartjs/PolarChart",
    component: _f292ad46,
    name: "charts-chartjs-PolarChart___es"
  }, {
    path: "/es/charts/chartjs/RadarChart",
    component: _01bab695,
    name: "charts-chartjs-RadarChart___es"
  }, {
    path: "/es/dashboard/analytics/channels",
    component: _9d1d8b6e,
    name: "dashboard-analytics-channels___es"
  }, {
    path: "/es/dashboard/analytics/overview",
    component: _5b670772,
    name: "dashboard-analytics-overview___es"
  }, {
    path: "/es/dashboard/analytics/social-media",
    component: _0ab5d97d,
    name: "dashboard-analytics-social-media___es"
  }, {
    path: "/es/dashboard/analytics/sources",
    component: _43d8664f,
    name: "dashboard-analytics-sources___es"
  }, {
    path: "/es/dashboard/analytics/users",
    component: _27aba45f,
    name: "dashboard-analytics-users___es"
  }, {
    path: "/es/ecommerce/customers/data",
    component: _27a59807,
    name: "ecommerce-customers-data___es"
  }, {
    path: "/es/ecommerce/orders/data",
    component: _6be6c7af,
    name: "ecommerce-orders-data___es"
  }, {
    path: "/es/ecommerce/products/data",
    component: _70f8c42e,
    name: "ecommerce-products-data___es"
  }, {
    path: "/es/tables/advanced/data",
    component: _281c10cd,
    name: "tables-advanced-data___es"
  }, {
    path: "/es/task/kanban/data",
    component: _4307787c,
    name: "task-kanban-data___es"
  }, {
    path: "/fr/apps/calendar/data-calendar",
    component: _0980eb07,
    name: "apps-calendar-data-calendar___fr"
  }, {
    path: "/fr/apps/chat/data",
    component: _40288a56,
    name: "apps-chat-data___fr"
  }, {
    path: "/fr/apps/companies/data",
    component: _3ab0e5d9,
    name: "apps-companies-data___fr"
  }, {
    path: "/fr/apps/tickets/data",
    component: _a1b7a236,
    name: "apps-tickets-data___fr"
  }, {
    path: "/fr/charts/apex/data",
    component: _22fd905d,
    name: "charts-apex-data___fr"
  }, {
    path: "/fr/charts/c3/data",
    component: _e0335eaa,
    name: "charts-c3-data___fr"
  }, {
    path: "/fr/charts/chartist/data",
    component: _1c8b42a7,
    name: "charts-chartist-data___fr"
  }, {
    path: "/fr/charts/chartjs/BarChart",
    component: _961f6d30,
    name: "charts-chartjs-BarChart___fr"
  }, {
    path: "/fr/charts/chartjs/DonutChart",
    component: _ebb54c0e,
    name: "charts-chartjs-DonutChart___fr"
  }, {
    path: "/fr/charts/chartjs/LineChart",
    component: _7c3cd1bd,
    name: "charts-chartjs-LineChart___fr"
  }, {
    path: "/fr/charts/chartjs/PieChart",
    component: _60122c0f,
    name: "charts-chartjs-PieChart___fr"
  }, {
    path: "/fr/charts/chartjs/PolarChart",
    component: _f292ad46,
    name: "charts-chartjs-PolarChart___fr"
  }, {
    path: "/fr/charts/chartjs/RadarChart",
    component: _01bab695,
    name: "charts-chartjs-RadarChart___fr"
  }, {
    path: "/fr/dashboard/analytics/channels",
    component: _9d1d8b6e,
    name: "dashboard-analytics-channels___fr"
  }, {
    path: "/fr/dashboard/analytics/overview",
    component: _5b670772,
    name: "dashboard-analytics-overview___fr"
  }, {
    path: "/fr/dashboard/analytics/social-media",
    component: _0ab5d97d,
    name: "dashboard-analytics-social-media___fr"
  }, {
    path: "/fr/dashboard/analytics/sources",
    component: _43d8664f,
    name: "dashboard-analytics-sources___fr"
  }, {
    path: "/fr/dashboard/analytics/users",
    component: _27aba45f,
    name: "dashboard-analytics-users___fr"
  }, {
    path: "/fr/ecommerce/customers/data",
    component: _27a59807,
    name: "ecommerce-customers-data___fr"
  }, {
    path: "/fr/ecommerce/orders/data",
    component: _6be6c7af,
    name: "ecommerce-orders-data___fr"
  }, {
    path: "/fr/ecommerce/products/data",
    component: _70f8c42e,
    name: "ecommerce-products-data___fr"
  }, {
    path: "/fr/tables/advanced/data",
    component: _281c10cd,
    name: "tables-advanced-data___fr"
  }, {
    path: "/fr/task/kanban/data",
    component: _4307787c,
    name: "task-kanban-data___fr"
  }, {
    path: "/ar/ecommerce/product-detail/:id?",
    component: _731a4efe,
    name: "ecommerce-product-detail-id___ar"
  }, {
    path: "/ar/email/reademail/:id?",
    component: _767f6f99,
    name: "email-reademail-id___ar"
  }, {
    path: "/es/ecommerce/product-detail/:id?",
    component: _731a4efe,
    name: "ecommerce-product-detail-id___es"
  }, {
    path: "/es/email/reademail/:id?",
    component: _767f6f99,
    name: "email-reademail-id___es"
  }, {
    path: "/fr/ecommerce/product-detail/:id?",
    component: _731a4efe,
    name: "ecommerce-product-detail-id___fr"
  }, {
    path: "/fr/email/reademail/:id?",
    component: _767f6f99,
    name: "email-reademail-id___fr"
  }, {
    path: "/ecommerce/product-detail/:id?",
    component: _731a4efe,
    name: "ecommerce-product-detail-id___en"
  }, {
    path: "/email/reademail/:id?",
    component: _767f6f99,
    name: "email-reademail-id___en"
  }, {
    path: "/",
    component: _7a6dbb4c
  }],

  fallback: false
}

export function createRouter () {
  return new Router(routerOptions)
}
